{{- if and .Values.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mycurelocal.fullname" . }}
  namespace: {{ include "mycurelocal.namespace" . }}
  labels:
    {{- include "mycurelocal.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mycurelocal.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
{{- end }}
