{{- if and .Values.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mycurelocal.fullname" . }}
  namespace: {{ include "mycurelocal.namespace" . }}
  labels:
    {{- include "mycurelocal.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "mycurelocal.selectorLabels" . | nindent 6 }}
{{- end }}
