{{- if and .Values.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mycurelocal.fullname" . }}
  namespace: {{ include "mycurelocal.namespace" . }}
  labels:
    {{- include "mycurelocal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mycurelocal.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
{{- end }}
