apiVersion: v2
name: dentalemon-myaccount
description: DentaLemon MyAccount - Account management for DentaLemon
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - dentalemon-myaccount
  - frontend
  - vue
  - healthcare
  - dental
home: https://github.com/monobaselabs/monobase-infra
sources:
  - https://github.com/monobaselabs/monobase
maintainers:
  - name: Your Organization
    email: devops@example.com
