{{- if and .Values.enabled .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "dentalemon-seeder.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "dentalemon-seeder.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "dentalemon-seeder.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: mongo-uri
      remoteRef:
        key: {{ .Values.externalSecrets.mongoUriKey }}
{{- end }}
