{{- if .Values.gateway.listeners }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ include "nginx-gateway.namespace" . }}
  labels:
    {{- include "nginx-gateway.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      hostname: {{ .hostname | quote }}
      allowedRoutes:
        namespaces:
          from: All
      {{- if eq .protocol "HTTPS" }}
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: {{ .tlsSecretName }}
      {{- end }}
    {{- end }}
{{- end }}
