{{- if and .Values.enabled .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ include "grafana.namespace" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "grafana.gateway.name" . }}
      namespace: {{ include "grafana.gateway.namespace" . }}
  hostnames:
    {{- if .Values.gateway.hostnames }}
    {{- range .Values.gateway.hostnames }}
    - {{ . }}
    {{- end }}
    {{- else }}
    - {{ include "grafana.gateway.hostname" . }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana
          port: 3000
          weight: 1
{{- end }}
