{{- if and .Values.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mycure-myaccount.fullname" . }}
  namespace: {{ include "mycure-myaccount.namespace" . }}
  labels:
    {{- include "mycure-myaccount.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "mycure-myaccount.selectorLabels" . | nindent 6 }}
{{- end }}
