{{- if and .Values.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dentalemon-website.fullname" . }}
  namespace: {{ include "dentalemon-website.namespace" . }}
  labels:
    {{- include "dentalemon-website.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dentalemon-website.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "dentalemon-website.gateway.namespace" . }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
{{- end }}
