{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dentalemon-website.serviceAccountName" . }}
  namespace: {{ include "dentalemon-website.namespace" . }}
  labels:
    {{- include "dentalemon-website.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
