{{- if and .Values.enabled .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myaccount.fullname" . }}
  namespace: {{ include "myaccount.namespace" . }}
  labels:
    {{- include "myaccount.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
