{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mycure-deploydash.serviceAccountName" . }}
  namespace: {{ include "mycure-deploydash.namespace" . }}
  labels:
    {{- include "mycure-deploydash.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
