apiVersion: v2
name: mycure-deploydash
description: MyCure DeployDash - Deployment dashboard application for MyCure
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mycure-deploydash
  - frontend
  - dashboard
  - healthcare
home: https://github.com/monobaselabs/monobase-infra
sources:
  - https://github.com/monobaselabs/monobase
maintainers:
  - name: Your Organization
    email: devops@example.com
